auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 0

ingester:
  wal:
    enabled: true
    dir: /tmp/loki/wal
  chunk_idle_period: 1h
  chunk_block_size: 262144
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-index
    cache_location: /tmp/loki/tsdb-cache
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: true

query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

ruler:
  alertmanager_url: http://localhost:9093
